[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "cd frontend/my-react-app",
  "npm ci",
  "npm run build"
]

[start]
cmd = "npx serve frontend/my-react-app/dist -l $PORT"
